### ISSUE TITLE
License should be LGPL 2.1

### ISSUE THREAD

**Issue by bperrybap** [WCRSyyc/LiquidCrystal595#1]
This library code came from Rowan Simms which was a derivative of the Stephen Hobley code which was a derivative of the Arduino IDE LiquidCrystal  library  as indicated by this comment in Stephen's code:
```
 * Adaption of the LiquidCrystal library shipped with Arduino 22
 * for use with 74HC595 shift register adapter
```

The LiquidCrystal library is licensed as LGPL 2.1+
Which means that this code can not be re-licensed as MIT.

**Comment by mMerlin** [comment]
That information looks reasonable. Where can the Hobley code be found? The only reference I have is the one line in the .h and .cpp files, and the Simms code did not have any license (or other attribution) information that I could see.

**Comment by bperrybap** [comment]
Best I can tell Rowan's code is archived here:
https://bitbucket.org/rowansimms/arduino-lcd-3pin/src/master/
It is clearly based on the Hobley code, and he even says as much:

> Stephen Hobley deserves a lot of credit, he was the original creator of this code.

And this appears to be an early (perhaps the first reference) to Stephen Hobley's project code going back to 2011.
http://www.stephenhobley.com/blog/2011/02/07/controlling-an-lcd-with-just-3-pins/

If you look at the code in the LiquidCrystal595 library it is clearly derived from the IDE LiquidCrystal code as
most of the code, structure, and text match up with the LiquidCrystal code from that time period.
And Stephen even says as much on that blog page:

> I updated the Arduino (22 release) LiquidCrystal library to use the 595 board. Download is here.

----------------------

It is understandable that Licensing of early versions of the LiquidCrystal library (pre 2015) is ambiguous and confusing since
the Arduino.cc team was originally very sloppy with copyrights and licensing, particularly back in the 2011 time frame when the LiquidCrystal595 library as created.

I pushed the Arduino.cc developers to get things straightened out starting back in the 2008/2009 time frame and several years later, back around 2015, they finally went in and did lots of updates to the IDE bundled libraries to more clearly indicate the proper licensing.
But this was *after* Hobley created the LiquidCrystal595 library.

The history of LiquidCrystal (like many of the other IDE bundled libraries) is particularly bad.
The actual license was not in the library code itself but buried down in another part of the Arduino development tree.

Here is a overview about it:
While the IDE LiquidCrystal code did not originally contain copyright notices or license
information in the LiquidCrystal source files themselves,
the IDE LiquidCrystal code was licensed as LGPL 2.1 as indicated in the
license.txt file in the root directory of the arduino.cc IDE repository which
was committed October 11, 2007 and has not changed since.
It can be seen here:
https://github.com/arduino/Arduino/blob/master/license.txt
license.txt was a catchall license for all
Arduino core files and libraries provided by the IDE.
It contains a small note:
```
next, the gnu lesser general public license that covers the arduino core
and libraries.
```
What is below that tiny comment in the readme file is a LGPL 2.1 license agreement.
So it seems that the intent was that the LiquidCrystal library was released as LGPL 2.1

In 2015 the IDE LiquidCrystal source files were updated to contain a copyright notice and
license within the files.

```
Copyright (C) 2006-2008 Hans-Christoph Steiner. All rights reserved.
Copyright (c) 2010 Arduino LLC. All right reserved.
```

[ with a LGPL 2.1+ notice ]

**Comment by bperrybap** [comment]
Just as an FYI, in the absence of a licensing agreement on s/w, one has to assume a strict copyright by the original author with no licensing and that it is not allowed to ever re-publish or share the work, including if there are any changes made to it.
This also means that anyone in possession of the code, cannot simply assign a license and then publish/release/share the code under that license.

This is why I pushed so hard for the Arduino.cc developers to get their copyrights and licensing information straightened up.
Because, back in early days, when the licensing was not obvious, people would have to assume a strict copyright with no licensing which meant they could not modify, or republish any of the Arduino code.
Clearly that was not the intent.

**Comment by mMerlin** [comment]
Digging into the (cloned) examples that come with the library, it looks like the original author is not arduino.cc.  Comments in the examples say:

```
 Library originally added 18 Apr 2008
 by David A. Mellis
 library modified 5 Jul 2009
 by Limor Fried (http://www.ladyada.net)
```

Even though it is/was published/hosted on arduino.cc, along with the tutorial.

Updated license file, added references to the .cpp and .h, added a chain for the known history.

How does that look?

**Comment by bperrybap** [comment]
I think the LGPL 2.1 license looks fine.
As long as the code is licensed as LGPL 2.1 it should be fine.

The true history of the LiquidCrystal library is a bit vague,  but my understanding is that it was as stated in the current LiquidCrystal sources. Arduino.cc was not really involved with any of its development, and that the code came from Hans-Christoph Steiner back in 2006. Mellis (from Ardino.cc) worked with or got the code from Seiner and committed it to the IDE bundled libraries at some point as a LGPL 2.1 licensed library, then a few years later it was modified & updated by Fried (Lady Ada) to its current form.
And eventually in 2015 Arduino.cc added proper copyright notices to the code and proper licensing was included with the library.

I seem to remember back in the 2015 time frame that Limor wanted it to be licensed MIT after her updates but that wasn't possible since the code started out as  LGPL 2.1
